gui:
  editor: "nvr --remote-wait-silent"
  showIcons: false
  sidePanelWidth: 0.2
  theme:
    textColor:
      - '#959696'
    unstagedChangesColor:
      - '#d6746b'
    stagedFileColor:
      - '#c7d6d6'
    defaultFgColor:
      - '#b9e1eb'
    selectedLineBgColor:
      - '#66737d'
    activeBorderColor:
      - '#bee8c8'
      - bold
    inactiveBorderColor:
      - '#889599'
  showFileTree: true # for rendering changes files in a tree format
keybinding:
  universal:
    quit: "q"
promptToReturnFromSubprocess: false
disableStartupPopups: true
git:
  paging:
    colorArg: always
    pager: delta --light --paging=never --diff-so-fancy --true-color=always 
    # pager: ydiff -s -p cat --wrap --width={{columnWidth}}
    # pager: diff-so-fancy
