gui:
  editor: "nvr --remote-wait-silent"
  showIcons: false
  sidePanelWidth: 0.2
  theme:
    unstagedChangesColor:
      - '#d5e2f7'
    defaultFgColor:
      - '#b9e1eb'
  showFileTree: true # for rendering changes files in a tree format
os:
  # editCommand: "nvim"
  # editCommandTemplate: "{{editor}} {{filename}}"
  # editPreset: 'nvim-remote'
  # edit: "nvr --remote-send '<C-space>:q<CR><Esc>:lua vim.cmd(\"e \" .. {{filename}})<CR>'"
  # editAtLine: "nvr --remote-send '<C-space>:q<CR><Esc>:lua vim.cmd(\"e \" .. {{filename}})<CR>{{line}}G'"
keybinding:
  universal:
    quit: "q"
promptToReturnFromSubprocess: false
disableStartupPopups: true
git:
  paging:
    colorArg: always
    pager: delta --light --paging=never --diff-so-fancy --true-color=always 
    # pager: ydiff -s -p cat --wrap --width={{columnWidth}}
    # pager: diff-so-fancy
